### ISSUE TITLE
iui = "0.3" in toml - not work, require git folder. Git method - work.

### ISSUE THREAD

**Issue by ghost** [rust-native-ui/libui-rs#109]
Windows Server 2019

```
error: failed to run custom build command for `ui-sys v0.1.3`
Caused by:
  process didn't exit successfully: `D:\Projects\Test\target\debug\build\ui-sys-54eef348477f7dd2\build-script-build` (exit code: 101)
  --- stdout
  git version 2.30.0.windows.1
  running: "cmake" "D:\\Rust\\cargo\\registry\\src\\github.com-1ecc6299db9ec823\\ui-sys-0.1.3\\libui" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=D:\\Projects\\Test\\target\\debug\\build\\ui-sys-9f5ae8adb4cc987e\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=release"
  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at '
  failed to execute command: The system cannot find the file specified. (os error 2)
  is `cmake` not installed?
  build script failed, must exit now', D:\Rust\cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:894:5
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4\/library\std\src\panicking.rs:493
     1: std::panicking::begin_panic_fmt
               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4\/library\std\src\panicking.rs:435
     2: cmake::fail
               at D:\Rust\cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:894
     3: cmake::run
               at D:\Rust\cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:864
     4: cmake::Config::build
               at D:\Rust\cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:707
     5: build_script_build::main
               at .\build.rs:35
     6: core::ops::function::FnOnce::call_once<fn(),tuple<>>
               at D:\Rust\rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
Process finished with exit code 101
```

**Comment by gbj** [comment]
I’ll just add that I experienced the same thing trying to build IUI for the first time on my Mac today; using this repo in Cargo.toml solved it for me as well.

**Comment by nashley** [comment]
#86 removed the dependency on `cmake`, but that hasn't made it into a release yet. I suspect that installing `cmake` would let you compile with the released version, but that's nearly 3 years old at this point, so it's probably a good idea to stick with using the git version.

**Comment by quickdudley** [comment]
I get the same error if I try to use iui from GitHub as a dependency in another crate, but if I run `cd libui-rs/iui; cargo build` it compiles without error.

**Comment by vstojkovic** [comment]
If people are still interested in this, I just ran into a bunch of issues with the `cmake` dependency, on Windows 10, and managed to solve them successfully. First, make sure that you install CMake and that it's version is no newer than 3.19. Second, make sure CMake is on your path. The installer can add it there, or you can set it manually. These two things should allow you to build `iui` version 0.3.0 without problems.

In case anyone is wondering why CMake 3.19, here's an explanation. The `build.rs` script in `ui-sys` uses the `cmake` crate incorrectly, by specifying an empty build target instead of calling `no_build_target(true)`. This results in the command line option `--target ""` being passed to CMake, which used to work fine with older CMake version. CMake 3.15 added support for multiple build targets, but empty build target still worked the same as omitting the `--target` switch. Starting with CMake 3.20, specifying an empty target triggers the usage message, which breaks the `ui-sys` build.

**Comment by NoraCodes** [comment]
For what it's worth, I'm likely to have some free time from work soon and hopefully can take the time to fix the build script. Thank you all for this very useful discussion!

**Comment by kleinesfilmroellchen** [comment]
This still happens on Windows 10 with version 0.3. (trunk has some different issues with bindgen not finding clang so couldn't test that.) It's very unfortunate that this requires an outdated cmake version (I only have 3.22) and I don't want users of my project to have to apply these hacks in order to get IUI compiling.

**Comment by Shadowblitz16** [comment]
I have this issue to and I'm on debian linux...
```
error: failed to run custom build command for `ui-sys v0.1.3`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `/home/shadowblitz16/Documents/source/rust/editor_x/target/debug/build/ui-sys-3bb4076e5b658a3b/build-script-build` (exit status: 101)
  --- stdout
  git version 2.47.3
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/shadowblitz16/Documents/source/rust/editor_x/target/debug/build/ui-sys-ca751e40ca93cea1/out/build" && CMAKE_PREFIX_PATH="" LC_ALL="C" "cmake" "/home/shadowblitz16/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ui-sys-0.1.3/libui" "-DCMAKE_INSTALL_PREFIX=/home/shadowblitz16/Documents/source/rust/editor_x/target/debug/build/ui-sys-ca751e40ca93cea1/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=release"
  -- Configuring incomplete, errors occurred!
  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.
    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.
    Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
  thread 'main' panicked at /home/shadowblitz16/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cmake-0.1.54/src/lib.rs:1119:5:
  command did not execute successfully, got: exit status: 1
  build script failed, must exit now
  stack backtrace:
     0: __rustc::rust_begin_unwind
               at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/panicking.rs:697:5
     1: core::panicking::panic_fmt
               at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/panicking.rs:75:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

```
Operating System: Debian GNU/Linux 13
KDE Plasma Version: 6.3.6
KDE Frameworks Version: 6.13.0
Qt Version: 6.8.2
Kernel Version: 6.12.43+deb13-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 16 GiB of RAM (11.6 GiB usable)
Graphics Processor: AMD Radeon Graphics
```
